# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-19 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl', '0003_auto_20170419_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pill',
            name='medicine_name',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name=b'Medicine Name'),
        ),
    ]
