# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250, verbose_name=b'SPL Display Name')),
                ('code', models.CharField(max_length=250, verbose_name=b'SPL Code')),
                ('hex_value', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'HEX Value')),
            ],
        ),
        migrations.CreateModel(
            name='Export',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Enabled?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_type', models.CharField(choices=[(b'json', b'JSON'), (b'csv', b'CSV'), (b'yaml', b'YAML'), (b'xml', b'XML')], max_length=200, verbose_name=b'File Type')),
                ('file_name', models.CharField(max_length=200, verbose_name=b'File Name')),
                ('export_file', models.FileField(blank=True, null=True, upload_to=b'export', verbose_name=b'Export File')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed?')),
                ('task_id', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Task ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Status')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name=b'Duration (Sec.)')),
            ],
            options={
                'verbose_name': 'Export',
                'verbose_name_plural': 'Export',
            },
        ),
        migrations.CreateModel(
            name='Import',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Enabled?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'File Name')),
                ('csv_file', models.FileField(upload_to=b'csv', verbose_name=b'CSV File')),
                ('completed', models.BooleanField(default=False, verbose_name=b'Completed?')),
                ('added', models.IntegerField(blank=True, null=True, verbose_name=b'Reocrds Added')),
                ('updated', models.IntegerField(blank=True, null=True, verbose_name=b'Records Updated')),
                ('task_id', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Task ID')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Status')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name=b'Duration (Sec.)')),
            ],
            options={
                'verbose_name': 'Data Import',
                'verbose_name_plural': 'Data Import',
            },
        ),
        migrations.CreateModel(
            name='PillBoxData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name=b'Enabled?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('setid', models.CharField(max_length=250, unique=True, verbose_name=b'spp')),
                ('setid_product', models.CharField(max_length=250, verbose_name=b'setid')),
                ('splsize', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splsize')),
                ('pillbox_size', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'pillbox_size')),
                ('splshape', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splshape')),
                ('splshape_text', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splshape_text')),
                ('pillbox_shape_text', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'pillbox_shape_text')),
                ('splscore', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splscore')),
                ('pillbox_score', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'pillbox_score')),
                ('splimprint', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splimprint')),
                ('pillbox_imprint', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'pillbox_imprint')),
                ('splcolor', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splcolor')),
                ('splcolor_text', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'splcolor_text')),
                ('pillbox_color_text', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'pillbox_color_text')),
                ('spl_strength', models.TextField(blank=True, null=True, verbose_name=b'spl_strength')),
                ('spl_ingredients', models.TextField(blank=True, null=True, verbose_name=b'spl_ingredients')),
                ('spl_inactive_ing', models.TextField(blank=True, null=True, verbose_name=b'spl_inactive_ing')),
                ('source', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'source')),
                ('rxtty', models.TextField(blank=True, null=True, verbose_name=b'rxtty')),
                ('rxstring', models.TextField(blank=True, null=True, verbose_name=b'rxtty')),
                ('rxcui', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'rxcui')),
                ('produce_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'product_code')),
                ('part_num', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'part_num')),
                ('part_medicine_name', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'part_medicine_name')),
                ('ndc9', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'ndc9')),
                ('medicine_name', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'medicine_name')),
                ('marketing_act_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'marketing_act_code')),
                ('effective_time', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'effective_time')),
                ('file_name', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'file_name')),
                ('equal_product_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'equal_product_code')),
                ('dosage_form', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'dosage_form')),
                ('document_type', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'document_type')),
                ('dea_schedule_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'dea_schedule_code')),
                ('dea_schedule_name', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'dea_schedule_name')),
                ('author_type', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'author_type')),
                ('author', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'author')),
                ('approval_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'approval_code')),
                ('image_source', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'image_source')),
                ('splimage', models.FileField(blank=True, max_length=250, null=True, upload_to=b'pillbox', verbose_name=b'splimage')),
                ('has_image', models.BooleanField(default=False, verbose_name=b'has_image')),
                ('from_sis', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'epc_match')),
                ('version_number', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'version_number')),
                ('laberer_code', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'laberer_code')),
                ('application_number', models.CharField(blank=True, max_length=250, null=True, verbose_name=b'application_number')),
                ('updated', models.BooleanField(default=False, verbose_name=b'updated')),
                ('stale', models.BooleanField(default=False, verbose_name=b'stale')),
                ('new', models.BooleanField(default=False, verbose_name=b'new')),
            ],
            options={
                'verbose_name': 'Pillbox Data',
                'verbose_name_plural': 'Pillbox Data',
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250, verbose_name=b'SPL Display Name')),
                ('code', models.CharField(max_length=250, verbose_name=b'SPL Code')),
            ],
        ),
    ]
