# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 21:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('spl', '0001_initial'),
        ('pillbox', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Imprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spl_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'SPL Value')),
                ('pillbox_value', models.CharField(blank=True, max_length=200, null=True, verbose_name=b'Pillbox Value')),
                ('verified', models.BooleanField(default=False, verbose_name=b'Verified?')),
                ('is_different', models.BooleanField(default=False, verbose_name=b'Is Different?')),
                ('reason', models.TextField(blank=True, null=True, verbose_name=b'Reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pillbox', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pillbox.PillBoxData')),
                ('spl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spl.Pill')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
