# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-04-20 01:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pillboxdata',
            old_name='from_sis',
            new_name='epc_match',
        ),
    ]
