# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-02 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0002_auto_20170419_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillboxdata',
            name='ndc_labeler_code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=b'ndc_labeler_code'),
        ),
        migrations.AddField(
            model_name='pillboxdata',
            name='ndc_product_code',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name=b'ndc_product_code'),
        ),
    ]
