# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-27 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0003_auto_20170702_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillboxdata',
            name='rx_update_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name=b'RxNorm Update time'),
        ),
    ]
