# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-07-27 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pillbox', '0004_pillboxdata_rx_update_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='pillboxdata',
            name='has_pillbox_value',
            field=models.BooleanField(default=False, verbose_name=b'Pillbox Value'),
        ),
    ]
